library(ggplot2)
library(dplyr)

df <- readRDS("data/processed/empty_generated_0_shift_28.rds")

# Calculate velocity if not already calculated
df <- df %>%
  group_by(Coord_Index) %>%
  arrange(Iteration) %>%
  mutate(
    velocity_X = X - lag(X),
    velocity_Y = Y - lag(Y),
    velocity_Z = Z - lag(Z)
  ) %>%
  filter(!is.na(velocity_X))  # Remove NA values generated by lag()

# Function to plot velocity over time for each Coord_Index
plot_velocity <- function(coord_index_data) {
  ggplot(coord_index_data, aes(x = Iteration)) +
    geom_line(aes(y = velocity_X, color = "X Axis"), size = 1) +
    geom_line(aes(y = velocity_Y, color = "Y Axis"), size = 1) +
    geom_line(aes(y = velocity_Z, color = "Z Axis"), size = 1) +
    labs(title = paste("Velocity over Time for Coord_Index", unique(coord_index_data$Coord_Index)),
         x = "Iteration", y = "Velocity") +
    scale_color_manual(values = c("X Axis" = "red", "Y Axis" = "green", "Z Axis" = "blue")) +
    theme_minimal()
}

# Loop through each Coord_Index and plot velocity
unique_coord_indexes <- unique(df$Coord_Index)
for (coord_index in unique_coord_indexes) {
  coord_index_data <- df %>% filter(Coord_Index == coord_index)
  plot <- plot_velocity(coord_index_data)
  print(plot)
}
