# This pipeline is for building latex file once pushed to main.
name: Build Reports

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Fetch reports branch
        run: |
          git fetch origin reports

      - name: Find changed files in reports folder
        run: |
          output=$(git diff --name-only ${{ github.sha }} origin/reports)
          if [ -n  "$output" ]; then
            echo "$output" | grep -E '^reports/.*\.tex$' > reports/changed_files.txt
          else
            exit 0
          fi

      - name: Install latex package
        run: sudo apt-get install texlive-latex-extra make

      - name: Generate aux
        run: |
          cd reports
          while IFS= read -r file; do
              pdflatex "$(basename $file)"
          done < changed_files.txt

      - name: Build bib
        run: |
          cd reports
          while IFS= read -r file; do
              bibtex "$(basename $file .tex)"
          done < changed_files.txt

      - name: Use bib
        run: |
          cd reports
          while IFS= read -r file; do
              pdflatex "$(basename $file)"
          done < changed_files.txt

      - name: Final latex
        run: |
          cd reports
          while IFS= read -r file; do
              pdflatex "$(basename $file)"
          done < changed_files.txt

      - name: Stash changes
        run: |
          git stash --all

      - name: Commit and push
        run: |
          git checkout reports --
          rm reports/*.pdf
          git stash apply
          git add -f reports/*.pdf
          git add reports/*.tex
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "Build reports (SHA: ${{ github.sha }})" || true
          git push origin reports --

