name: Build Reports

on:
  push:
    branches: [ report/test ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Find changed files in reports folder
        run: |
          git diff --name-only ${{ github.sha }}~1 | grep -E '^reports/.*\.tex$' > reports/changed_files.txt

      - name: Check if there are any changed files
        run: |
          if [[ ! -s changed_files.txt ]]; then
            exit 0;
          fi

      - name: Install latex package
        run: sudo apt-get install texlive-latex-extra make

      - name: Generate aux
        run: |
          cd reports
          while IFS= read -r file; do
              pdflatex "$(basename $file)".tex
          done < changed_files.txt

      - name: Build bib
        run: |
          cd reports
          while IFS= read -r file; do
              bibtex "$(basename $file)"
          done < changed_files.txt

      - name: Use bib
        run: |
          cd reports
          while IFS= read -r file; do
              pdflatex "$(basename $file)".tex
          done < changed_files.txt

      - name: Final latex
        run: |
          cd reports
          while IFS= read -r file; do
              pdflatex "$(basename $file)".tex
          done < changed_files.txt

      - name: Stash changes
        run: |
          git stash --all
          git fetch origin reports

      - name: Commit and push
        run: |
          git checkout reports --
          git stash apply
          git add -f reports/*.pdf
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "Build reports (SHA: ${{ github.sha }})" || true
          git push origin reports --

